# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 761, 591))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap(":/fondo/fondo.jpg"))
        self.fondo.setObjectName("fondo")
        self.codigo_fuente = QtWidgets.QTextEdit(self.centralwidget)
        self.codigo_fuente.setGeometry(QtCore.QRect(20, 70, 701, 171))
        self.codigo_fuente.setObjectName("codigo_fuente")
        self.consola = QtWidgets.QTextEdit(self.centralwidget)
        self.consola.setGeometry(QtCore.QRect(20, 320, 701, 201))
        self.consola.setObjectName("consola")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionAnalizar = QtWidgets.QAction(MainWindow)
        self.actionAnalizar.setObjectName("actionAnalizar")
        self.actionLimpiar = QtWidgets.QAction(MainWindow)
        self.actionLimpiar.setObjectName("actionLimpiar")
        self.menuOpciones.addAction(self.actionImportar)
        self.menuOpciones.addAction(self.actionAnalizar)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionLimpiar)
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))
        self.actionImportar.setText(_translate("MainWindow", "Importar"))
        self.actionAnalizar.setText(_translate("MainWindow", "Analizar"))
        self.actionLimpiar.setText(_translate("MainWindow", "Limpiar"))
#Poner fondo me da error
#import fondo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
