# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setEnabled(False)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 761, 591))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap(":/fondo/fondo.jpg"))
        self.fondo.setObjectName("fondo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 741, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ticketing")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.codigo_fuente = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.codigo_fuente.setObjectName("codigo_fuente")
        self.verticalLayout.addWidget(self.codigo_fuente)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ticketing")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.consola = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.consola.setObjectName("consola")
        self.verticalLayout.addWidget(self.consola)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ticketing")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.errores = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.errores.setObjectName("errores")
        self.verticalLayout.addWidget(self.errores)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionAnalizar = QtWidgets.QAction(MainWindow)
        self.actionAnalizar.setObjectName("actionAnalizar")
        self.actionLimpiar = QtWidgets.QAction(MainWindow)
        self.actionLimpiar.setObjectName("actionLimpiar")
        self.actionAnalizarSyntax = QtWidgets.QAction(MainWindow)
        self.actionAnalizarSyntax.setObjectName("actionAnalizarSyntax")
        self.menuOpciones.addAction(self.actionImportar)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionLimpiar)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.actionAnalizar)
        self.menuOpciones.addAction(self.actionAnalizarSyntax)
        self.menuOpciones.addSeparator()
        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Código"))
        self.label_2.setText(_translate("MainWindow", "Análisis"))
        self.label_3.setText(_translate("MainWindow", "Errores"))
        self.menuOpciones.setTitle(_translate("MainWindow", "Opciones"))
        self.actionImportar.setText(_translate("MainWindow", "Importar"))
        self.actionAnalizar.setText(_translate("MainWindow", "Analizador Léxico"))
        self.actionLimpiar.setText(_translate("MainWindow", "Limpiar"))
        self.actionAnalizarSyntax.setText(_translate("MainWindow", "Analizador SintácticoSemántico"))
#import fondo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
